config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/cocktails', to: 'cocktails#index'
  get '/cocktails/new', to: 'cocktails#new'
  post '/cocktails', to: 'cocktails#create'
  get '/cocktails/:id', to: 'cocktails#show', as: :cocktail
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates_uniqueness_of :cocktail_id, :scope => [:ingredient_id]
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses

  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
    def index
      @cocktails = Cocktail.all
    end

    def show
      @cocktail = Cocktail.find(params[:id])
    end

    def new
      @cocktail = Cocktail.new
    end

    def create
      @cocktail = Cocktail.new(cocktail_params)
      @cocktail.save
    end

    private

    def cocktail_params
      params.require(:cocktail).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/views/cocktails/_form.html.erb
<%= form_for(@cocktail) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :ingredient %>
  <%= f.text_field :ingredient %>
  <%= f.submit %>
<% end %>

app/views/cocktails/index.html.erb
<h1>Cocktails</h1>

<% @cocktails.each do |drink| %>
  <p><%= link_to "#{drink.name}", cocktail_path(drink) %></p>
<% end %>

app/views/cocktails/new.html.erb
<h1>Make a new cocktail</h1>

<%= render "form", cocktail: @cocktail %>

app/views/cocktails/show.html.erb
<h1><%= @cocktail.name %></h1>
<ul><% @cocktail.doses.each do |dose| %>
  <li><%= dose.description %><%= dose.ingredient.name %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>